name = "IsoTNS"
uuid = "e1432803-13fb-461b-8ed1-07954e4d353e"
authors = ["Qingyuan <qingyuan@QingyuandeMacBook-Air.local> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
